spring:
  application:
    name: persona-gateway
  cloud:
    consul:
      discovery:
        register: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
server:
  port: 8000